ekyna_admin:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: ekyna_admin_dashboard
        permanent: true

ekyna_admin_dashboard:
    path:  /admin/dashboard
    methods: [GET]
    defaults:
        _controller: EkynaAdminBundle:Dashboard:index

ekyna_admin_security_login:
    path: /admin/login
    methods: [GET]
    defaults:
        _controller: EkynaAdminBundle:Security:login

ekyna_admin_security_check:
    path: /admin/login-check
    methods: [POST]
    defaults:
        _controller: EkynaAdminBundle:Security:check

ekyna_admin_security_logout:
    path: /admin/logout

ekyna_admin_barcode:
    path:  /admin/barcode/{barcode}
    methods: [GET]
    defaults:
        _controller: Ekyna\Bundle\AdminBundle\Controller\ToolbarController::barcode
    options:
        expose: true

ekyna_admin_admin:
    resource: "routing/admin.yml"
    prefix: /admin
