admin:
    path: '%ekyna_admin.routing_prefix%'
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: admin_dashboard
        permanent: true

admin_dashboard:
    path: '%ekyna_admin.routing_prefix%/dashboard'
    methods: [ GET ]
    controller: Ekyna\Bundle\AdminBundle\Controller\DashboardController

admin_security:
    resource: routing/security.yaml
    prefix: '%ekyna_admin.routing_prefix%'

admin_api:
    resource: routing/api.yaml
    prefix: '%ekyna_admin.routing_prefix%/api'

admin_pin:
    resource: routing/pin.yaml
    prefix: '%ekyna_admin.routing_prefix%/pins'

admin_toolbar:
    resource: routing/toolbar.yaml
    prefix: '%ekyna_admin.routing_prefix%/toolbar'

admin_ekyna_oauth:
    resource: .
    type: ekyna_admin_oauth

admin_ekyna_resource:
    resource: .
    type: admin_resource
