ekyna_admin_toolbar_search:
    path:  /search
    methods: [POST]
    defaults:
        _controller: Ekyna\Bundle\AdminBundle\Controller\ToolbarController::search
    options:
        expose: true

ekyna_admin_toolbar_barcode:
    path:  /barcode/{barcode}
    methods: [GET]
    defaults:
        _controller: Ekyna\Bundle\AdminBundle\Controller\ToolbarController::barcode
    options:
        expose: true
