# Liip Imagine
liip_imagine:
    filter_sets:
        admin_table:
            quality: 70
            data_loader: local_image
            filters:
                thumbnail: { size: [24, 24], mode: outbound }
            post_processors:
                jpegoptim: {}
        admin_thumb:
            quality: 70
            data_loader: local_image
            filters:
                thumbnail: { size: [145, 109], mode: outbound }
            post_processors:
                jpegoptim: {}
        admin_modal:
            quality: 70
            data_loader: local_image
            filters:
                thumbnail: { size: [800, 600], mode: inset }
                background: { size: [800, 600], color: '#fff' }
            post_processors:
                jpegoptim: {}