ekyna_admin_pin_remove:
    path:  /{id}/remove
    methods: [GET]
    defaults:
        _controller: EkynaAdminBundle:Pin:remove
    options:
        expose: true

ekyna_admin_pin_resource_pin:
    path:  /resource/{name}/{identifier}/pin
    methods: [GET]
    defaults:
        _controller: EkynaAdminBundle:Pin:resourcePin
    options:
        expose: true

ekyna_admin_pin_resource_unpin:
    path:  /resource/{name}/{identifier}/unpin
    methods: [GET]
    defaults:
        _controller: EkynaAdminBundle:Pin:resourceUnpin
    options:
        expose: true
